# Dependencies
markdown:            redcarpet
highlighter:         pygments

# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               Cody Bunch
tagline:             'Some Random IT Guy - OpenStack, DevOps, Cloud, Things'
description:         'Offering all manner of technical how-to (and how not to) and other technical content. I specalize in OpenStack, VMware, and most things automation and cloud related.'
url:                 http://lanyon.getpoole.com
baseurl:             /
paginate:            5

# About/contact
author:
  name:              Cody Bunch
  url:               https://blog.codybunch.com
  email:             bunchc@gmail.com

# Custom vars
version:             1.0.0
